spring.datasource.url=jdbc:postgresql://dpg-d8ak8ejeo5us739oh1s0-a/hospital_management_xsxj
spring.datasource.username=hospital_user
spring.datasource.password=..Abhishek18..

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false