server.port=${PORT:8080}
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.oeaiwcemuvikrznrwwrj&password=..Abhishek18..
spring.datasource.username=postgres.oeaiwcemuvikrznrwwrj
spring.datasource.password=..Abhishek18..
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.thymeleaf.cache=false