spring.datasource.url=jdbc:postgresql://db.oeaiwcemuvikrznrwwrj.supabase.co:5432/postgres?user=postgres&password=[YOUR-PASSWORD]
spring.datasource.username=postgres
spring.datasource.password=..Abhishek18..

spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.cache=false